package org.garde.model;

// Generated 26 janv. 2012 14:00:05 by Hibernate Tools 3.4.0.CR1

/**
 * Activite generated by hbm2java
 */
public class Activite implements java.io.Serializable {

	private Integer activiteId;
	private String nom;

	public Activite() {
	}

	public Activite(String nom) {
		this.nom = nom;
	}

	public Integer getActiviteId() {
		return this.activiteId;
	}

	public void setActiviteId(Integer activiteId) {
		this.activiteId = activiteId;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	// The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = 1L;

	public String toString() {
		return getNom();
	}

	// end of extra code specified in the hbm.xml files

}
