package org.garde.model;

// Generated 28 mars 2012 11:32:37 by Hibernate Tools 3.4.0.CR1

/**
 * Activite generated by hbm2java
 */
public class Activite implements java.io.Serializable {

	private Integer activiteId;
	private String nom;
	private String comment;

	public Activite() {
	}

	public Activite(String nom, String comment) {
		this.nom = nom;
		this.comment = comment;
	}

	public Integer getActiviteId() {
		return this.activiteId;
	}

	public void setActiviteId(Integer activiteId) {
		this.activiteId = activiteId;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	// The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = 1L;

	public String toString() {
		return getNom();
	}

	// end of extra code specified in the hbm.xml files

}
