package org.garde.model;

// Generated 26 janv. 2012 14:00:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Astreinte generated by hbm2java
 */
public class Astreinte implements java.io.Serializable {

	private Integer astreinteId;
	private Date debut;
	private Date fin;
	private Activite activite;
	private Personnel personnel;

	public Astreinte() {
	}

	public Astreinte(Date debut, Date fin, Activite activite,
			Personnel personnel) {
		this.debut = debut;
		this.fin = fin;
		this.activite = activite;
		this.personnel = personnel;
	}

	public Integer getAstreinteId() {
		return this.astreinteId;
	}

	public void setAstreinteId(Integer astreinteId) {
		this.astreinteId = astreinteId;
	}

	public Date getDebut() {
		return this.debut;
	}

	public void setDebut(Date debut) {
		this.debut = debut;
	}

	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	public Activite getActivite() {
		return this.activite;
	}

	public void setActivite(Activite activite) {
		this.activite = activite;
	}

	public Personnel getPersonnel() {
		return this.personnel;
	}

	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}

}
