package org.garde.model;

// Generated 28 mars 2012 11:32:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Personnel generated by hbm2java
 */
public class Personnel implements java.io.Serializable {

	private Integer personnelId;
	private String titre;
	private String nom;
	private String prenom;
	private String telMobile;
	private String telPerso;
	private String telPro;
	private String commentaire;
	private Set affectations = new HashSet(0);

	public Personnel() {
	}

	public Personnel(String titre, String nom, String prenom, String telMobile,
			String telPerso, String telPro, String commentaire, Set affectations) {
		this.titre = titre;
		this.nom = nom;
		this.prenom = prenom;
		this.telMobile = telMobile;
		this.telPerso = telPerso;
		this.telPro = telPro;
		this.commentaire = commentaire;
		this.affectations = affectations;
	}

	public Integer getPersonnelId() {
		return this.personnelId;
	}

	public void setPersonnelId(Integer personnelId) {
		this.personnelId = personnelId;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getTelMobile() {
		return this.telMobile;
	}

	public void setTelMobile(String telMobile) {
		this.telMobile = telMobile;
	}

	public String getTelPerso() {
		return this.telPerso;
	}

	public void setTelPerso(String telPerso) {
		this.telPerso = telPerso;
	}

	public String getTelPro() {
		return this.telPro;
	}

	public void setTelPro(String telPro) {
		this.telPro = telPro;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public Set getAffectations() {
		return this.affectations;
	}

	public void setAffectations(Set affectations) {
		this.affectations = affectations;
	}

}
