package strutsbase;

// Generated 28 mars 2012 11:32:37 by Hibernate Tools 3.4.0.CR1

/**
 * UsersGroup generated by hbm2java
 */
public class UsersGroup implements java.io.Serializable {

	private Integer id;
	private String label;

	public UsersGroup() {
	}

	public UsersGroup(Integer id) {
		this.id = id;
	}

	public UsersGroup(Integer id, String label) {
		this.id = id;
		this.label = label;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
